proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30080

hub:
  config:
    JupyterHub:
      authenticator_class: dummy
    DummyAuthenticator:
      password: "shared-hackathon-password"
    Authenticator:
      admin_users:
        - admin
proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30080

singleuser:
  image:
    name: quay.io/jupyter/scipy-notebook
    tag: latest
  extraResource:
    limits:
      nvidia.com/mig-1g.12gb: 1
  cpu:
    limit: 4
    guarantee: 2
  memory:
    limit: 16G
    guarantee: 8G
  storage:
    capacity: 20Gi
